from legged_gym import LEGGED_GYM_ROOT_DIR, LEGGED_GYM_ENVS_DIR
from legged_gym.envs.go2.go2_config import GO2RoughCfg, GO2RoughCfgPPO
from legged_gym.envs.rs01_go2_straight import (
    Rs01Go2Kp40Cfg,
    Rs01Go2Kp40CfgPPO,
    Rs01Go2Kp40PolishCfg,
    Rs01Go2Kp40PolishCfgPPO,
    Rs01Go2PathPolishCfg,
    Rs01Go2PathPolishCfgPPO,
    Rs01Go2RearCoordCfg,
    Rs01Go2RearCoordCfgPPO,
    Rs01Go2Sim2SimAdaptCfg,
    Rs01Go2Sim2SimAdaptCfgPPO,
    Rs01Go2Sim2SimCalfRepairCfg,
    Rs01Go2Sim2SimCalfRepairCfgPPO,
    Rs01Go2Sim2SimKd050Cfg,
    Rs01Go2Sim2SimKd050CfgPPO,
    Rs01Go2Sim2SimRobustCfg,
    Rs01Go2Sim2SimRobustCfgPPO,
    Rs01Go2MatchedTransferCfg,
    Rs01Go2MatchedTransferCfgPPO,
    Rs01Go2Heading52Cfg,
    Rs01Go2Heading52CfgPPO,
    Rs01Go2Model930DriftRepairCfg,
    Rs01Go2Model930DriftRepairCfgPPO,
    Rs01Go2Model1425Path54Cfg,
    Rs01Go2Model1425Path54CfgPPO,
    Rs01Go2Path54Sim2SimTransferCfg,
    Rs01Go2Path54Sim2SimTransferCfgPPO,
    Rs01Go2EstimatorParityCfg,
    Rs01Go2EstimatorParityCfgPPO,
    Rs01Go2StraightCfg,
    Rs01Go2StraightCfgPPO,
    Rs01Go2StraightRobot,
)
from legged_gym.envs.dog import (
    DogRs01Robot,
    DogRs01TrotCfg,
    DogRs01TrotCfgPPO,
    DogRs01BalanceCfg,
    DogRs01BalanceCfgPPO,
    DogRs01BodyStableCfg,
    DogRs01BodyStableCfgPPO,
    DogRs01LowTwistCfg,
    DogRs01LowTwistCfgPPO,
    DogRs01HipTorqueCfg,
    DogRs01HipTorqueCfgPPO,
    DogRs01StraightBalanceCfg,
    DogRs01StraightBalanceCfgPPO,
    DogRs01CompactHipCfg,
    DogRs01CompactHipCfgPPO,
    DogRs01SafeTorquePathCfg,
    DogRs01SafeTorquePathCfgPPO,
    DogRs01SafeTorquePathV2Cfg,
    DogRs01SafeTorquePathV2CfgPPO,
    DogRs01SmoothStraightCfg,
    DogRs01SmoothStraightCfgPPO,
    DogRs01SmoothStraightV2Cfg,
    DogRs01SmoothStraightV2CfgPPO,
    DogRs01StraightGuardedCfg,
    DogRs01StraightGuardedCfgPPO,
    DogRs01TorqueStraightV5Cfg,
    DogRs01TorqueStraightV5CfgPPO,
    DogRs01Stage2ActuatorACfg,
    DogRs01Stage2ActuatorACfgPPO,
    DogRs01Stage2ActuatorBCfg,
    DogRs01Stage2ActuatorBCfgPPO,
    DogRs01StraightStandCfg,
    DogRs01StraightStandCfgPPO,
    DogRs01StraightWalkCfg,
    DogRs01StraightWalkCfgPPO,
)
from legged_gym.envs.fanfan.fanfan_config import FanfanRoughCfg, FanfanRoughCfgPPO
from legged_gym.envs.fanfan.fanfan_env import FanfanRobot
from legged_gym.envs.fanfan.fanfan_omni_safe_config import (
    FanfanOmniSafeCfg,
    FanfanOmniSafeCfgPPO,
    FanfanOmniFastCfg,
    FanfanOmniFastCfgPPO,
    FanfanOmniSmoothRealCfg,
    FanfanOmniSmoothRealCfgPPO,
    FanfanOmniFilteredCfg,
    FanfanOmniFilteredCfgPPO,
    FanfanOmniVelTrackV3Cfg,
    FanfanOmniVelTrackV3CfgPPO,
    FanfanOmniLateralFixCfg,
    FanfanOmniLateralFixCfgPPO,
    FanfanOmniLateralSpeedCleanCfg,
    FanfanOmniLateralSpeedCleanCfgPPO,
    FanfanOmniDesatTorqueCfg,
    FanfanOmniDesatTorqueCfgPPO,
    FanfanOmniYawDriftCleanCfg,
    FanfanOmniYawDriftCleanCfgPPO,
    FanfanOmniYawSymmetryCfg,
    FanfanOmniYawSymmetryCfgPPO,
    FanfanOmniYawPathFixCfg,
    FanfanOmniYawPathFixCfgPPO,
    FanfanOmniDiagonalCoordCfg,
    FanfanOmniDiagonalCoordCfgPPO,
    FanfanOmniCoordinatedStraightCfg,
    FanfanOmniCoordinatedStraightCfgPPO,
    FanfanOmniProjectedCoordCfg,
    FanfanOmniProjectedCoordCfgPPO,
    FanfanOmniStrongSymmetryCfg,
    FanfanOmniStrongSymmetryCfgPPO,
    FanfanOmniNoCompSymmetryCfg,
    FanfanOmniNoCompSymmetryCfgPPO,
    FanfanOmniHeadingBoundSymmetryCfg,
    FanfanOmniHeadingBoundSymmetryCfgPPO,
    FanfanOmniForceCoordCfg,
    FanfanOmniForceCoordCfgPPO,
    FanfanOmniForceDesatCfg,
    FanfanOmniForceDesatCfgPPO,
    FanfanOmniHighSpeedTransitionCfg,
    FanfanOmniHighSpeedTransitionCfgPPO,
    FanfanOmniHighAuthorityTransitionCfg,
    FanfanOmniHighAuthorityTransitionCfgPPO,
    FanfanOmniHighAuthorityDirectionCfg,
    FanfanOmniHighAuthorityDirectionCfgPPO,
    FanfanOmniHighAuthorityClosedLoopCfg,
    FanfanOmniHighAuthorityClosedLoopCfgPPO,
    FanfanOmniHighCadenceCfg,
    FanfanOmniHighCadenceCfgPPO,
    FanfanOmniSymmetricTransitionCfg,
    FanfanOmniSymmetricTransitionCfgPPO,
    FanfanOmniTiltRecovery5530Cfg,
    FanfanOmniTiltRecovery5530CfgPPO,
    FanfanOmniHardwareBalance5530Cfg,
    FanfanOmniHardwareBalance5530CfgPPO,
    FanfanOmniHardwareBalance5530V2Cfg,
    FanfanOmniHardwareBalance5530V2CfgPPO,
    FanfanOmniRealDataCurriculumCfg,
    FanfanOmniRealDataCurriculumCfgPPO,
    FanfanOmniRealDataSpeedPolishCfg,
    FanfanOmniRealDataSpeedPolishCfgPPO,
    FanfanOmniRealDataCoordinatedCfg,
    FanfanOmniRealDataCoordinatedCfgPPO,
    FanfanOmniRealDataClearancePolishCfg,
    FanfanOmniRealDataClearancePolishCfgPPO,
    FanfanOmniRealDataDirectionalPolishCfg,
    FanfanOmniRealDataDirectionalPolishCfgPPO,
    FanfanOmniRealDataPerformanceRecoveryCfg,
    FanfanOmniRealDataPerformanceRecoveryCfgPPO,
    FanfanOmniCalibratedSymmetryCfg,
    FanfanOmniCalibratedSymmetryCfgPPO,
)
from legged_gym.envs.fanfan_rouhe.fanfan_config import (
    FanfanRouheRoughCfg,
    FanfanRouheRoughCfgPPO,
)
from legged_gym.envs.fanfan_rouhe.fanfan_env import FanfanRouheRobot
from legged_gym.envs.h1.h1_config import H1RoughCfg, H1RoughCfgPPO
from legged_gym.envs.h1.h1_env import H1Robot
from legged_gym.envs.h1_2.h1_2_config import H1_2RoughCfg, H1_2RoughCfgPPO
from legged_gym.envs.h1_2.h1_2_env import H1_2Robot
from legged_gym.envs.g1.g1_config import G1RoughCfg, G1RoughCfgPPO
from legged_gym.envs.g1.g1_env import G1Robot
from .base.legged_robot import LeggedRobot
from legged_gym.utils.task_registry import task_registry as task_registry

task_registry.register("go2", LeggedRobot, GO2RoughCfg(), GO2RoughCfgPPO())
task_registry.register(
    "rs01_go2_straight",
    Rs01Go2StraightRobot,
    Rs01Go2StraightCfg(),
    Rs01Go2StraightCfgPPO(),
)
task_registry.register(
    "rs01_go2_straight_rear_coord",
    Rs01Go2StraightRobot,
    Rs01Go2RearCoordCfg(),
    Rs01Go2RearCoordCfgPPO(),
)
task_registry.register(
    "rs01_go2_straight_path_polish",
    Rs01Go2StraightRobot,
    Rs01Go2PathPolishCfg(),
    Rs01Go2PathPolishCfgPPO(),
)
task_registry.register(
    "rs01_go2_straight_kp40",
    Rs01Go2StraightRobot,
    Rs01Go2Kp40Cfg(),
    Rs01Go2Kp40CfgPPO(),
)
task_registry.register(
    "rs01_go2_straight_kp40_polish",
    Rs01Go2StraightRobot,
    Rs01Go2Kp40PolishCfg(),
    Rs01Go2Kp40PolishCfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_adapt",
    Rs01Go2StraightRobot,
    Rs01Go2Sim2SimAdaptCfg(),
    Rs01Go2Sim2SimAdaptCfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_calf_repair",
    Rs01Go2StraightRobot,
    Rs01Go2Sim2SimCalfRepairCfg(),
    Rs01Go2Sim2SimCalfRepairCfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_kd050",
    Rs01Go2StraightRobot,
    Rs01Go2Sim2SimKd050Cfg(),
    Rs01Go2Sim2SimKd050CfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_robust",
    Rs01Go2StraightRobot,
    Rs01Go2Sim2SimRobustCfg(),
    Rs01Go2Sim2SimRobustCfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_matched_transfer",
    Rs01Go2StraightRobot,
    Rs01Go2MatchedTransferCfg(),
    Rs01Go2MatchedTransferCfgPPO(),
)
task_registry.register(
    "rs01_go2_sim2sim_heading52",
    Rs01Go2StraightRobot,
    Rs01Go2Heading52Cfg(),
    Rs01Go2Heading52CfgPPO(),
)
task_registry.register(
    "rs01_go2_model930_drift_repair",
    Rs01Go2StraightRobot,
    Rs01Go2Model930DriftRepairCfg(),
    Rs01Go2Model930DriftRepairCfgPPO(),
)
task_registry.register(
    "rs01_go2_model1425_path54",
    Rs01Go2StraightRobot,
    Rs01Go2Model1425Path54Cfg(),
    Rs01Go2Model1425Path54CfgPPO(),
)
task_registry.register(
    "rs01_go2_path54_sim2sim_transfer",
    Rs01Go2StraightRobot,
    Rs01Go2Path54Sim2SimTransferCfg(),
    Rs01Go2Path54Sim2SimTransferCfgPPO(),
)
task_registry.register(
    "rs01_go2_estimator_parity",
    Rs01Go2StraightRobot,
    Rs01Go2EstimatorParityCfg(),
    Rs01Go2EstimatorParityCfgPPO(),
)
task_registry.register(
    "dog_rs01_trot", DogRs01Robot, DogRs01TrotCfg(), DogRs01TrotCfgPPO()
)
task_registry.register(
    "dog_rs01_balance", DogRs01Robot, DogRs01BalanceCfg(), DogRs01BalanceCfgPPO()
)
task_registry.register(
    "dog_rs01_body_stable",
    DogRs01Robot,
    DogRs01BodyStableCfg(),
    DogRs01BodyStableCfgPPO(),
)
task_registry.register(
    "dog_rs01_low_twist", DogRs01Robot, DogRs01LowTwistCfg(), DogRs01LowTwistCfgPPO()
)
task_registry.register(
    "dog_rs01_hip_torque", DogRs01Robot, DogRs01HipTorqueCfg(), DogRs01HipTorqueCfgPPO()
)
task_registry.register(
    "dog_rs01_straight_balance",
    DogRs01Robot,
    DogRs01StraightBalanceCfg(),
    DogRs01StraightBalanceCfgPPO(),
)
task_registry.register(
    "dog_rs01_compact_hip",
    DogRs01Robot,
    DogRs01CompactHipCfg(),
    DogRs01CompactHipCfgPPO(),
)
task_registry.register(
    "dog_rs01_safe6nm",
    DogRs01Robot,
    DogRs01SafeTorquePathCfg(),
    DogRs01SafeTorquePathCfgPPO(),
)
task_registry.register(
    "dog_rs01_safe6nm_v2",
    DogRs01Robot,
    DogRs01SafeTorquePathV2Cfg(),
    DogRs01SafeTorquePathV2CfgPPO(),
)
task_registry.register(
    "dog_rs01_smooth_straight",
    DogRs01Robot,
    DogRs01SmoothStraightCfg(),
    DogRs01SmoothStraightCfgPPO(),
)
task_registry.register(
    "dog_rs01_smooth_straight_v2",
    DogRs01Robot,
    DogRs01SmoothStraightV2Cfg(),
    DogRs01SmoothStraightV2CfgPPO(),
)
task_registry.register(
    "dog_rs01_straight_guarded",
    DogRs01Robot,
    DogRs01StraightGuardedCfg(),
    DogRs01StraightGuardedCfgPPO(),
)
task_registry.register(
    "dog_rs01_torque_straight_v5",
    DogRs01Robot,
    DogRs01TorqueStraightV5Cfg(),
    DogRs01TorqueStraightV5CfgPPO(),
)
task_registry.register(
    "dog_rs01_stage2_actuator_a",
    DogRs01Robot,
    DogRs01Stage2ActuatorACfg(),
    DogRs01Stage2ActuatorACfgPPO(),
)
task_registry.register(
    "dog_rs01_stage2_actuator_b",
    DogRs01Robot,
    DogRs01Stage2ActuatorBCfg(),
    DogRs01Stage2ActuatorBCfgPPO(),
)
task_registry.register(
    "dog_rs01_straight_stand",
    DogRs01Robot,
    DogRs01StraightStandCfg(),
    DogRs01StraightStandCfgPPO(),
)
task_registry.register(
    "dog_rs01_straight_walk",
    DogRs01Robot,
    DogRs01StraightWalkCfg(),
    DogRs01StraightWalkCfgPPO(),
)
task_registry.register("fanfan", FanfanRobot, FanfanRoughCfg(), FanfanRoughCfgPPO())
task_registry.register(
    "fanfan_omni_safe", FanfanRobot, FanfanOmniSafeCfg(), FanfanOmniSafeCfgPPO()
)
task_registry.register(
    "fanfan_omni_fast", FanfanRobot, FanfanOmniFastCfg(), FanfanOmniFastCfgPPO()
)
task_registry.register(
    "fanfan_omni_smooth_real",
    FanfanRobot,
    FanfanOmniSmoothRealCfg(),
    FanfanOmniSmoothRealCfgPPO(),
)
task_registry.register(
    "fanfan_omni_filtered",
    FanfanRobot,
    FanfanOmniFilteredCfg(),
    FanfanOmniFilteredCfgPPO(),
)
task_registry.register(
    "fanfan_omni_veltrack_v3",
    FanfanRobot,
    FanfanOmniVelTrackV3Cfg(),
    FanfanOmniVelTrackV3CfgPPO(),
)
task_registry.register(
    "fanfan_omni_lateral_fix",
    FanfanRobot,
    FanfanOmniLateralFixCfg(),
    FanfanOmniLateralFixCfgPPO(),
)
task_registry.register(
    "fanfan_omni_lateral_speed_clean",
    FanfanRobot,
    FanfanOmniLateralSpeedCleanCfg(),
    FanfanOmniLateralSpeedCleanCfgPPO(),
)
task_registry.register(
    "fanfan_omni_desat_torque",
    FanfanRobot,
    FanfanOmniDesatTorqueCfg(),
    FanfanOmniDesatTorqueCfgPPO(),
)
task_registry.register(
    "fanfan_rouhe", FanfanRouheRobot, FanfanRouheRoughCfg(), FanfanRouheRoughCfgPPO()
)
task_registry.register("h1", H1Robot, H1RoughCfg(), H1RoughCfgPPO())
task_registry.register("h1_2", H1_2Robot, H1_2RoughCfg(), H1_2RoughCfgPPO())
task_registry.register("g1", G1Robot, G1RoughCfg(), G1RoughCfgPPO())
task_registry.register(
    "fanfan_omni_yaw_drift_clean",
    FanfanRobot,
    FanfanOmniYawDriftCleanCfg(),
    FanfanOmniYawDriftCleanCfgPPO(),
)
task_registry.register(
    "fanfan_omni_yaw_symmetry",
    FanfanRobot,
    FanfanOmniYawSymmetryCfg(),
    FanfanOmniYawSymmetryCfgPPO(),
)
task_registry.register(
    "fanfan_omni_yaw_path_fix",
    FanfanRobot,
    FanfanOmniYawPathFixCfg(),
    FanfanOmniYawPathFixCfgPPO(),
)
task_registry.register(
    "fanfan_omni_diagonal_coord",
    FanfanRobot,
    FanfanOmniDiagonalCoordCfg(),
    FanfanOmniDiagonalCoordCfgPPO(),
)
task_registry.register(
    "fanfan_omni_coordinated_straight",
    FanfanRobot,
    FanfanOmniCoordinatedStraightCfg(),
    FanfanOmniCoordinatedStraightCfgPPO(),
)
task_registry.register(
    "fanfan_omni_projected_coord",
    FanfanRobot,
    FanfanOmniProjectedCoordCfg(),
    FanfanOmniProjectedCoordCfgPPO(),
)
task_registry.register(
    "fanfan_omni_strong_symmetry",
    FanfanRobot,
    FanfanOmniStrongSymmetryCfg(),
    FanfanOmniStrongSymmetryCfgPPO(),
)
task_registry.register(
    "fanfan_omni_no_comp_symmetry",
    FanfanRobot,
    FanfanOmniNoCompSymmetryCfg(),
    FanfanOmniNoCompSymmetryCfgPPO(),
)
task_registry.register(
    "fanfan_omni_heading_bound_symmetry",
    FanfanRobot,
    FanfanOmniHeadingBoundSymmetryCfg(),
    FanfanOmniHeadingBoundSymmetryCfgPPO(),
)
task_registry.register(
    "fanfan_omni_force_coord",
    FanfanRobot,
    FanfanOmniForceCoordCfg(),
    FanfanOmniForceCoordCfgPPO(),
)
task_registry.register(
    "fanfan_omni_force_desat",
    FanfanRobot,
    FanfanOmniForceDesatCfg(),
    FanfanOmniForceDesatCfgPPO(),
)
task_registry.register(
    "fanfan_omni_high_speed_transition",
    FanfanRobot,
    FanfanOmniHighSpeedTransitionCfg(),
    FanfanOmniHighSpeedTransitionCfgPPO(),
)
task_registry.register(
    "fanfan_omni_high_authority_transition",
    FanfanRobot,
    FanfanOmniHighAuthorityTransitionCfg(),
    FanfanOmniHighAuthorityTransitionCfgPPO(),
)
task_registry.register(
    "fanfan_omni_high_authority_direction",
    FanfanRobot,
    FanfanOmniHighAuthorityDirectionCfg(),
    FanfanOmniHighAuthorityDirectionCfgPPO(),
)
task_registry.register(
    "fanfan_omni_high_authority_closed_loop",
    FanfanRobot,
    FanfanOmniHighAuthorityClosedLoopCfg(),
    FanfanOmniHighAuthorityClosedLoopCfgPPO(),
)
task_registry.register(
    "fanfan_omni_high_cadence",
    FanfanRobot,
    FanfanOmniHighCadenceCfg(),
    FanfanOmniHighCadenceCfgPPO(),
)
task_registry.register(
    "fanfan_omni_symmetric_transition",
    FanfanRobot,
    FanfanOmniSymmetricTransitionCfg(),
    FanfanOmniSymmetricTransitionCfgPPO(),
)
task_registry.register(
    "fanfan_omni_tilt_recovery_5530",
    FanfanRobot,
    FanfanOmniTiltRecovery5530Cfg(),
    FanfanOmniTiltRecovery5530CfgPPO(),
)
task_registry.register(
    "fanfan_omni_hardware_balance_5530",
    FanfanRobot,
    FanfanOmniHardwareBalance5530Cfg(),
    FanfanOmniHardwareBalance5530CfgPPO(),
)
task_registry.register(
    "fanfan_omni_hardware_balance_5530_v2",
    FanfanRobot,
    FanfanOmniHardwareBalance5530V2Cfg(),
    FanfanOmniHardwareBalance5530V2CfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_curriculum",
    FanfanRobot,
    FanfanOmniRealDataCurriculumCfg(),
    FanfanOmniRealDataCurriculumCfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_speed_polish",
    FanfanRobot,
    FanfanOmniRealDataSpeedPolishCfg(),
    FanfanOmniRealDataSpeedPolishCfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_coordinated",
    FanfanRobot,
    FanfanOmniRealDataCoordinatedCfg(),
    FanfanOmniRealDataCoordinatedCfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_clearance_polish",
    FanfanRobot,
    FanfanOmniRealDataClearancePolishCfg(),
    FanfanOmniRealDataClearancePolishCfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_directional_polish",
    FanfanRobot,
    FanfanOmniRealDataDirectionalPolishCfg(),
    FanfanOmniRealDataDirectionalPolishCfgPPO(),
)
task_registry.register(
    "fanfan_omni_realdata_performance_recovery",
    FanfanRobot,
    FanfanOmniRealDataPerformanceRecoveryCfg(),
    FanfanOmniRealDataPerformanceRecoveryCfgPPO(),
)
task_registry.register(
    "fanfan_omni_calibrated_symmetry",
    FanfanRobot,
    FanfanOmniCalibratedSymmetryCfg(),
    FanfanOmniCalibratedSymmetryCfgPPO(),
)
